"""initial migration

Revision ID: a04a68b9db83
Revises:
Create Date: 2026-04-25 14:25:19.491139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text

# revision identifiers, used by Alembic.
revision: str = "a04a68b9db83"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("max_streak", sa.Integer(), nullable=False),
        sa.Column("learning_mode", sa.String(length=20), nullable=False, server_default="classic"),
        sa.Column("xp_multiplier", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("streak_freeze_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "ai_recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_plan", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_recommendations_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_recommendations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "drill_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("avg_response_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drill_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drill_sessions_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_drill_sessions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "sr_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("factor_a", sa.Integer(), nullable=False),
        sa.Column("factor_b", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("hints_remaining", sa.Integer(), nullable=False, server_default="3"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sr_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sr_cards_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sr_cards_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "sr_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["sr_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sr_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sr_reviews_card_id"), ["card_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sr_reviews_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sr_reviews_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sr_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sr_reviews_user_id"))
        batch_op.drop_index(batch_op.f("ix_sr_reviews_id"))
        batch_op.drop_index(batch_op.f("ix_sr_reviews_card_id"))

    op.drop_table("sr_reviews")
    with op.batch_alter_table("sr_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sr_cards_user_id"))
        batch_op.drop_index(batch_op.f("ix_sr_cards_id"))

    op.drop_table("sr_cards")
    with op.batch_alter_table("drill_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drill_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_drill_sessions_id"))

    op.drop_table("drill_sessions")
    with op.batch_alter_table("ai_recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_recommendations_user_id"))
        batch_op.drop_index(batch_op.f("ix_ai_recommendations_id"))

    op.drop_table("ai_recommendations")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
