"""add locked and hints_remaining to sr_cards

Revision ID: abc123456789
Revises: 002
Create Date: 2026-04-29 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abc123456789"
down_revision: Union[str, Sequence[str], None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sr_cards", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked", sa.Boolean(), nullable=False, server_default="false"))
        batch_op.add_column(sa.Column("hints_remaining", sa.Integer(), nullable=False, server_default="3"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sr_cards", schema=None) as batch_op:
        batch_op.drop_column("hints_remaining")
        batch_op.drop_column("locked")

    # ### end Alembic commands ###
